const testIds = {
	doubleClickButtonId: 'doubleClickBtn',
	doubleClickMessageId: 'doubleClickMessage',
	rightClickButtonId: 'rightClickBtn',
	rightClickMessageId: 'rightClickMessage',
	primaryButtonClass: 'btn-primary',
	dynamicClickMessageId: 'dynamicClickMessage',
	collapseButtonClass: 'rct-collapse-btn',
	titleClass: 'rct-title',
	expandAllClass: 'rct-option-expand-all',
	collapseAllClass: 'rct-option-collapse-all',
	nodeExpandedClasses: '.rct-node.rct-node-parent.rct-node-expanded',
	rctCheckboxClass: 'rct-checkbox',
	resultId: 'result',
	textSuccessClass: 'text-success',
	uncheckIconClasses: '.rct-icon.rct-icon-uncheck',
	textCenterClass: 'text-center',
	simpleLinkId: 'simpleLink',
	dynamicLinkId: 'dynamicLink',
	noContentId: 'no-content',
	movedId: 'moved',
	badRequestId: 'bad-request',
	unauthorizedId: 'unauthorized',
	forbiddenId: 'forbidden',
	invalidUrlId: 'invalid-url',
	loginId: 'login',
	newUserId: 'newUser',
	firstNameId: 'firstName',
	firstnameId: 'firstname',
	lastNameId: 'lastName',
	lastnameId: 'lastname',
	passwordId: 'password',
	registerId: 'register',
	nameId: 'name',
	yesRadioId: 'yesRadio',
	impressiveRadioId: 'impressiveRadio',
	noRadioId: 'noRadio',
	userFormId: 'userForm',
	submitId: 'submit',
	outputId: 'output',
	userEmailId: 'userEmail',
	userNameId: 'userName',
	emailId: 'email',
	currentAddressId: 'currentAddress',
	permanentAddressId: 'permanentAddress',
	webTablesWrapperClass: 'web-tables-wrapper',
	addNewRecordButtonId: 'addNewRecordButton',
	searchBoxId: 'searchBox',
	reactTableClass: 'ReactTable',
	editRecord1Class: 'edit-record-1',
	deleteRecord1Class: 'delete-record-1',
	modalContentClass: 'modal-content',
	ageId: 'age',
	salaryId: 'salary',
	departmentId: 'department',
	resizableHeadercontentClass: 'rt-resizable-header-content',
	sortAscClass: '-sort-asc',
	sortDescClass: '-sort-desc',
	oddClasses: 'rt-tr -odd',
};

module.exports = {
	testIds,
};
